name: Create ADR Generation Request
description: Issue that triggers the creation of a Architecture Decision Record
title: "[ADR-Gen-Req]: ADR Generation Request"
labels: [ADR Generation Request]

body:

  - type: markdown
    attributes:
      # yamllint disable rule:line-length
      value: |
        The new created issue will be used to generate a new ADR. The new ADR will be created in a new Pull Request.
        
  - type: dropdown
    id: adr-status
    attributes:
      label: Status
      description: The current status of the ADR?
      options:
        - proposed
        - rejected
        - accepted
        - deprecated

  - type: input
    id: adr-title
    attributes:
      label: ADR Title
      description:
        Title of solved problem and solution
      placeholder: short title of solved problem and solution
    validations:
      required: true

  - type: input
    id: adr-deciders
    attributes:
      label: Deciders
      description:
        List of people who can make the decision about the ADR
      placeholder: short title of solved problem and solution

  - type: input
    id: adr-consultants
    attributes:
      label: Consultants
      description:
        List of people who should be consulted about the ADR
      placeholder: short title of solved problem and solution

  - type: input
    id: adr-informed
    attributes:
      label: Informants
      description:
        List of people who should be informed about the ADR
      placeholder: short title of solved problem and solution
