# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on new issues
  issues:
    types: [opened]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}
    
      # Examples on how to use the output
      - name: Show parsed payload data
        run: |
          # Using the character `'` to prevent all characters enclosed within
          # them from being treated as special characters (e.g. $ or `)
          echo '${{ steps.parse.outputs.payload }}' > ${{ github.event.issue.number }}.json
          cat '${{ github.event.issue.number }}.json'

      - name: Create PR content
        run: |
          python3 ./create_adr_pr.py ${{ github.event.issue.number }} docs/decisions/adr-template.md

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}        
        with:
          commit-message: "Create PR"
          add-paths: "docs/decisions/*.md"
          title: "Test PR"
          body: "This is a test PR"
          branch: "test-pr"
          branch-suffix: "test-pr"
          delete-branch: true
          draft: true
